In [13]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}
docs = []
for a in documents:
    docs.append(a)
    print(a)


Article: Pandas Basics
Tutorial: Data Visualization
Case Study: Sales Analysis


In [14]:
# get the keys of the documents and store it in the list
key_documents = docs

# display the list of the key documents
print(key_documents)
    

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [26]:
# Extract the category of the key documents and store it 
cons = []
for a in docs:
    cons.append(a.split(":")[0])
print(cons)
    

['Article', 'Tutorial', 'Case Study']


In [53]:

# Extract the content values and put them in a list
document_content_list = []
for a in documents:
    document_content_list.append(documents.get(a))

# Display the list of document content
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [54]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = {term for doc in document_content_list for term in doc.split()}
unique_terms

{'Analyze',
 'Learn',
 'Pandas',
 'Python',
 'Python.',
 'This',
 'a',
 'about',
 'article',
 'basics',
 'case',
 'covers',
 'data',
 'for',
 'in',
 'libraries.',
 'of',
 'real-world',
 'sales',
 'study.',
 'techniques',
 'the',
 'using',
 'visualization',
 'with'}

In [56]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []
    
    for doc in document_content_list:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

# display the result of the matrix
doc_term_matrix

{'with': [0, 1, 0],
 'in': [1, 0, 1],
 'techniques': [0, 1, 0],
 'study.': [0, 0, 1],
 'for': [0, 0, 1],
 'case': [0, 0, 1],
 'Analyze': [0, 0, 1],
 'Pandas': [1, 0, 0],
 'covers': [1, 0, 0],
 'sales': [0, 0, 1],
 'Python': [1, 1, 1],
 'using': [1, 0, 1],
 'basics': [1, 0, 0],
 'a': [1, 1, 1],
 'real-world': [0, 0, 1],
 'of': [1, 0, 0],
 'the': [1, 0, 0],
 'about': [0, 1, 0],
 'article': [1, 0, 0],
 'libraries.': [0, 1, 0],
 'Learn': [0, 1, 0],
 'Python.': [1, 0, 0],
 'data': [0, 1, 1],
 'This': [1, 0, 0],
 'visualization': [0, 1, 0]}

In [66]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

search = [doc for doc in v3 * docs_array if doc]

# display the content document from the result
print(search)



[1 0 0]
[1 1 1]
-------
[1 0 0]
['This article covers the basics of using Pandas in Python.']


In [64]:
# find the document for those have at least one word

v1 = np.array(doc_term_matrix['data'])    
v2 = np.array(doc_term_matrix['for'])

print(v1)
print(v2)
print('-------')
v3 = v1 | v2
print(v3)

search = [doc for doc in v3 * docs_array if doc]

print(search)

[0 1 1]
[0 0 1]
-------
[0 0 1]
['Analyze sales data using Python for a real-world case study.']
